"""
Description: This script generates a a 25-bar stacked chart (5 methods by 5 folds) from split_stats.log.

- Bar color encodes split method (Random, Scaffold, Butina, UMAP_kmeans, UMAP_ward).
- Stacked segments show Train / Validation / Test counts for each fold.
- X-labels are "<method>\\nF<fold>".

Requirements:
- A split_stats.log file generated by your splitting script, e.g. from step 2 "Data splitting".
"""
import re
from pathlib import Path
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.patches import Patch
import seaborn as sns

# Paths
LOG_PATH = Path("p1_preprocessing/4 - Data splitting/2 - split_data/split_stats.log")
OUT_PATH = Path("p1_preprocessing/4 - Data splitting/3 - splits_data_visualization/bar_plot_distributions/split_distr.png")
OUT_PATH.parent.mkdir(parents=True, exist_ok=True)

# Plot parameters
GROUP_GAP = 4.0 
plt.rcParams["hatch.linewidth"] = 2.0

# Regex for parsing log lines
MAIN_LINE_RE = re.compile(
    r"\[(?P<split>\w+)\s*\|\s*fold\s*(?P<fold>\d+)\]\s*"
    r"train\s*(?P<train>[\d,]+)\s*\|\s*val\s*(?P<val>[\d,]+)\s*\|\s*test\s*(?P<test>[\d,]+)\s*\|"
    r"\s*actives≥(?P<thr>[\d\.]+)\s*val:\s*(?P<val_act>[\d,]+)\s*test:\s*(?P<test_act>[\d,]+)"
)

DISPLAY_NAME = {
    "random": "Random (stratified)",
    "scaffold": "Scaffold",
    "butina": "Butina",
    "umap_kmeans": "UMAP (k-means)",
    "umap_ward": "UMAP (ward)"}

DESIRED_ORDER = ["random", "scaffold", "butina", "umap_kmeans", "umap_ward"]

def parse_log(log_path: Path) -> pd.DataFrame:
    if not log_path.exists():
        raise FileNotFoundError(f"Log not found: {log_path}")
    recs = []
    for line in log_path.read_text().splitlines():
        m = MAIN_LINE_RE.search(line)
        if not m:
            continue
        to_int = lambda s: int(s.replace(",", ""))
        recs.append({
            "split": m.group("split"),
            "fold": int(m.group("fold")),
            "train_n": to_int(m.group("train")),
            "val_n": to_int(m.group("val")),
            "test_n": to_int(m.group("test")),
        })
    if not recs:
        raise ValueError("No split lines matched in the log.")
    df = pd.DataFrame.from_records(recs)

    present = list(df["split"].unique())
    order = [s for s in DESIRED_ORDER if s in present] + [s for s in present if s not in DESIRED_ORDER]
    df["split"] = pd.Categorical(df["split"], categories=order, ordered=True)
    return df.sort_values(["split", "fold"]).reset_index(drop=True)

# Make the plot
def make_plot(df: pd.DataFrame, out_path: Path):
    split_order = list(df["split"].cat.categories)
    folds = sorted(df["fold"].unique())
    n_groups = len(split_order)
    per_group = len(folds)

    labels, bars = [], []
    x_positions = []
    group_centers = []
    separators = []

    current = 0.0
    for gi, s in enumerate(split_order):
        group_pos = [current + j for j in range(per_group)]
        x_positions.extend(group_pos)

        for f in folds:
            row = df[(df["split"] == s) & (df["fold"] == f)].iloc[0]
            labels.append(str(f))  # numbers only, no "K="
            bars.append((s, int(row["train_n"]), int(row["val_n"]), int(row["test_n"])))

        group_centers.append(np.mean(group_pos))

        if gi < n_groups - 1:
            next_start = group_pos[-1] + GROUP_GAP + 1
            boundary = (group_pos[-1] + next_start) / 2.0
            separators.append(boundary)

        current = group_pos[-1] + GROUP_GAP + 1

    # Reds palette mid-tones; last method lighter
    cmap = sns.color_palette("Reds", as_cmap=True)
    positions = np.linspace(0.35, 0.85, n_groups)
    colors = [cmap(p) for p in positions]
    colors[-1] = cmap(0.30)
    method_color = {s: colors[i] for i, s in enumerate(split_order)}

    # Segment styles
    seg_style = {
        "Train": dict(hatch="", alpha=1.00),
        "Validation": dict(hatch="|", alpha=0.85),
        "Test": dict(hatch="/", alpha=0.70)}

    # Figure width
    effective_len = current
    fig_w = max(18, 0.35 * effective_len)
    fig, ax = plt.subplots(figsize=(fig_w, 7))

    for xsep in separators:
        ax.axvline(xsep, color="k", lw=0.8, alpha=0.15, zorder=0)

    # Stacked bars
    for (s, tr, vl, te), xpos in zip(bars, x_positions):
        c = method_color[s]
        bottom = 0
        ax.bar(xpos, tr, bottom=bottom, facecolor=c, edgecolor="black", **seg_style["Train"])
        bottom += tr
        ax.bar(xpos, vl, bottom=bottom, facecolor=c, edgecolor="black", **seg_style["Validation"])
        bottom += vl
        ax.bar(xpos, te, bottom=bottom, facecolor=c, edgecolor="black", **seg_style["Test"])

    # Bottom x ticks
    ax.set_xticks(x_positions)
    ax.set_xticklabels(labels, rotation=0)
    ax.set_xlabel("Fold (K)", fontsize=14)

    # Top x labels
    ax_top = ax.secondary_xaxis('top')
    ax_top.set_xticks(group_centers)
    ax_top.set_xticklabels([DISPLAY_NAME.get(s, s) for s in split_order])
    for t in ax_top.get_xticklabels():
        t.set_fontweight("semibold")

    ax.set_ylabel("Number of Molecules", fontsize=14)

    # Suptitle
    fig.suptitle("Split Composition by Method and Fold", fontsize=16, y=0.98)
    plt.subplots_adjust(top=0.90, bottom=0.22, left=0.08, right=0.85)

    # Handels for legend
    set_handles = [Patch(facecolor="white", edgecolor="black",
                         hatch=seg_style[name]["hatch"], label=name)
                   for name in ["Train", "Validation", "Test"]]
    ax.legend(handles=set_handles, title="Set", loc="upper left", bbox_to_anchor=(1.02, 1.02), borderaxespad=0.0)

    # Save
    fig.savefig(out_path, dpi=200, bbox_inches="tight")
    plt.close(fig)
    print(f"Saved: {out_path}")

def main():
    df = parse_log(LOG_PATH)
    make_plot(df, OUT_PATH)

if __name__ == "__main__":
    main()